In [5]:
import pandas as pd
import numpy as np

In [6]:
import os
import sys

In [7]:
dir = os.path.dirname(os.getcwd())
path = os.path.join(dir, "Network_Data","phishingData.csv")

In [8]:
df = pd.read_csv(path)

In [9]:
df.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [10]:
df.reset_index(drop=True,inplace=True)
df.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [ ]:
df.T.to_json()

In [ ]:
import json


records=list(json.loads(df.T.to_json()).values())
records

[{'having_IP_Address': -1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': -1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': -1,
  'Links_in_tags': 1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': -1,
  'RightClick': 1,
  'popUpWidnow': -1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': -1,
  'URL_Length': 0,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': -1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': -1,
  'URL_of_Anchor': -1,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 1,
  'Page_Rank': 1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': 1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': -1,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': -1,
  'URL_Length': 1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': -1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 0,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': -1,
  'Links_in_tags': 1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': -1,
  'RightClick': 1,
  'popUpWidnow': -1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': -1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': -1,
  'URL_of_Anchor': -1,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': 1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 1,
  'SFH': 1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': -1,
  'having_At_Symbol': -1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 0,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': -1,
  'URL_of_Anchor': -1,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 0,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': -1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 1,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': -1,
  'Page_Rank': 1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': -1,
  'RightClick': -1,
  'popUpWidnow': -1,
  'Iframe': -1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': -1,
  'RightClick': 1,
  'popUpWidnow': -1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 0,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': 1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': -1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': 1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': 1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 0,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': -1,
  'having_At_Symbol': -1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': 0,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': 1,
  'web_traffic': -1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 1,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': 1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': 1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': -1,
  'having_Sub_Domain': 0,
  'SSLfinal_State': -1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': -1,
  'Request_URL': -1,
  'URL_of_Anchor': -1,
  'Links_in_tags': -1,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': 1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': -1,
  'Result': -1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': 1,
  'Prefix_Suffix': 1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': 1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': -1,
  'URL_of_Anchor': 1,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': -1,
  'Abnormal_URL': -1,
  'Redirect': 0,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': 1,
  'DNSRecord': -1,
  'web_traffic': 0,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': 0,
  'Statistical_report': -1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': -1,
  'having_At_Symbol': 1,
  'double_slash_redirecting': -1,
  'Prefix_Suffix': 1,
  'having_Sub_Domain': -1,
  'SSLfinal_State': 1,
  'Domain_registeration_length': -1,
  'Favicon': 1,
  'port': 1,
  'HTTPS_token': 1,
  'Request_URL': 1,
  'URL_of_Anchor': 1,
  'Links_in_tags': 0,
  'SFH': -1,
  'Submitting_to_email': 1,
  'Abnormal_URL': 1,
  'Redirect': 1,
  'on_mouseover': 1,
  'RightClick': 1,
  'popUpWidnow': 1,
  'Iframe': 1,
  'age_of_domain': -1,
  'DNSRecord': -1,
  'web_traffic': 1,
  'Page_Rank': -1,
  'Google_Index': 1,
  'Links_pointing_to_page': -1,
  'Statistical_report': 1,
  'Result': 1},
 {'having_IP_Address': 1,
  'URL_Length': -1,
  'Shortining_Service': 1,